# triggers a release or a release candidate based on the version defined in package.json

name: Archive JetBrains Mono

on:
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Setup core dependencies
        run: |
          sudo apt update -y -q
          sudo apt install software-properties-common -y -q
          sudo apt install python3-fontforge -y -q
          sudo apt install fuse -y -q

      - name: Fetch FontForge
        run: |
          curl -L "https://github.com/fontforge/fontforge/releases/download/20230101/FontForge-2023-01-01-a1dad3e-x86_64.AppImage" \
            --output fontforge
          chmod u+x fontforge
          echo Try appimage
          ./fontforge --version
          export PATH=`pwd`:$PATH
          echo "PATH=$PATH" >> $GITHUB_ENV
          echo Try appimage with path
          fontforge --version

      # It is unclear what this has been needed for
      - name: Setup additional dependencies
        if: false
        run: |
          pip install fonttools --quiet

      # It is unclear what this has been needed for
      - name: Build FreeType from source
        if: false
        run: |
          wget http://downloads.sourceforge.net/project/freetype/freetype2/2.7/freetype-2.7.tar.gz --quiet
          tar -zxf freetype-2.7.tar.gz
          cd freetype-2.7
          ./configure
          make --quiet
          sudo make install --quiet

      # It is unclear what this has been needed for
      - name: Build Harfbuzz from source
        if: false
        run: |
          wget http://www.freedesktop.org/software/harfbuzz/release/harfbuzz-1.3.4.tar.bz2 --quiet
          tar -xjf harfbuzz-1.3.4.tar.bz2
          cd harfbuzz-1.3.4
          ./configure
          make --quiet
          sudo make install --quiet

      - name: Verify setup
        run: |
          fontforge --version
          fontforge --version 2>&1 | grep libfontforge | awk '{print $NF}'

      - name: Bump version for source files
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./version-bump.sh "$RELEASE_VERSION"

      - name: Standardize the readme files
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ./standardize-and-complete-readmes.sh "JetBrainsMono"

      - name: Patch all the variations of the font family
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          fontforge --script `pwd`/../../font-patcher --version
          ./gotta-patch-em-all-font-patcher\!.sh -j "/JetBrainsMono"

      - name: Archive font package zip files
        run: |
          cd -- "$GITHUB_WORKSPACE/bin/scripts"
          ls -lR ../../patched-fonts/JetBrainsMono
          ./archive-fonts.sh "JetBrainsMono"

